baseurl = "https://harmades.github.io/"
languageCode = "en-us"
title = "Magnificent Code"
theme = "blackburn"
author = "Adrian Lissot"
copyright = "&copy; 2019. All rights reserved."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Coding Blog"
  brand = "Adrian Lissot"
  googleAnalytics = "Your Google Analytics tracking ID"
  disqus = "Adrian"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter = "adrianlissot"
  github = "harmades"
  stackoverflow = "8784049/adrian-lissot"
  linkedin = "adrian-lissot-5a6981119"